Algoritmo "exercicio_71"
// programa que preenche automaticamente um vetor numérico
// com oito posições
Var

// INDICE
i: inteiro

vet: inteiro
val: vetor[0..7] de inteiro

Inicio
vet <- 999


// atribuindo valores para cada um dos vetores (do valor VAL)
val[0] <- 999
val[1] <- 999
val[2] <- 999
val[3] <- 999
val[4] <- 999
val[5] <- 999
val[6] <- 999
val[7] <- 999

Para i <- 0 ate 7 faca
Escreva ("[",val[i],"]")


Escreva ("(",i,")")


    
FimPara

// COMENTÁRIO:
// Dúvida na elaboração e por isso, predefini os valores
// de cada indice de "val". O primeiro é 0, o segundo é 1
// e assim por diante

Fimalgoritmo