Algoritmo "nome_maiusc_e_minusc"


// Faça um programa que leia o nome de um usuário e
// extraia apenas a primeira e a última letra desse nome.
// Para a primeira letra, use Copia(nome, 1, 1).
// Para a última, combine as funções Copia() e Compr()



Var
nome: caractere

Inicio
nome <- "Gabriel"

Escreval ("A primeira letra é: ",Copia(nome,1,1),".")
Escreval ("A última letra é: ",Copia(nome,7,7),".")


Fimalgoritmo