Algoritmo "regressiva_30_1"

Var
contador: inteiro

Inicio
contador <- 31
Enquanto contador>=1 faca
         contador <- contador - 1
                  se contador%4=0 entao
                  Escreva ("(")
                  Escreva (contador)
                  Escreval (")")
                  senao
                  Escreval (contador)
                  fimse
Fimenquanto
Fimalgoritmo