Algoritmo "contagem_3"

Var
 v1, v2, i, contador: inteiro
Inicio
 contador <- i
 Escreva ("DIGITE UM VALOR: ")
 Leia (v1)
 Escreva ("DIGITE UM VALOR: ")
 Leia (v2)
 Escreva ("INCREMENTO: ")
 Leia (i)
 Escreval ("Contando..............................................")
 Enquanto contador<=v2 faca
 Escreval (contador)
          contador <- contador + i
 fimenquanto
 Escreval ("  Acabou! ")
Fimalgoritmo